- name: check the facts
  hosts: localhost
  connection: local
  tasks:
  - name: install nginx if it is redhat
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "Redhat" # use ansible while refering the fact.

  - name: install nginx if redhat
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family == "Debian"