- name: functions
  hosts: localhost
  connection: local
  tasks:
  - name: default variable
    ansible.builtin.debug:
    #  msg: "Hello, {{ name }}"       # u got error because u did not define name elsewhere
       msg: "Hello, {{ name | default ('RAMESH') }}"