- name: variables from prompt
  hosts: localhost
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your username?
    private: false
  - name: password
    prompt: what is your password?
    private: true                           # password does not print in console while u type ok    24 min
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{ username }} password: {{ password }}"